import React from 'react';

const Home = React.lazy(() => import('../views/Home'));
const LearnMore = React.lazy(() => import('../views/LearnMore'));
const Subscribe = React.lazy(() => import('../views/Subscribe'));
const Partners = React.lazy(() => import('../views/Partners'));
const AboutToken = React.lazy(() => import('../views/AboutToken'));
const ContactUs = React.lazy(() => import('../views/ContactUs'));
const DetailSearch = React.lazy(() => import('../views/DetailSearch'));
const Cart = React.lazy(() => import('../views/Cart'));
const AboutUs = React.lazy(() => import('../views/AboutUs'));
const Product = React.lazy(() => import('../views/Product'));
const MyInsurance = React.lazy(() => import('../views/MyInsurance'));
const SubmitReview = React.lazy(() => import('../views/SubmitReview'));
const MsoPackages = React.lazy(() => import('../views/MsoPackages'));
const MsoProducts = React.lazy(() => import('../views/MsoProducts'));
const ErrorPage = React.lazy(() => import('../views/ErrorPage'));

const routes = [
  {
    path: '/',
    pageName: 'Home',
    exact: true,
    withSidebar: true,
    component: Home,
    showBuyButton: true,
    title: 'Motto of the Company',
    subtitle:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel semper blandit euismodvitae eleifend vitae eleifend massa imperdiet.',
    bgImg: 'HomePageBg',
    mobileBgImg: 'HomeMobileBg',
    bgImgClass: 'bg-100% bg-no-repeat bg-cover',
  },
  {
    path: '/learn-more',
    exact: true,
    pageName: 'LearnMore',
    withSidebar: true,
    showBuyButton: true,
    component: LearnMore,
    title: 'Learn More',
    bgImg: 'learnMoreBg',
    mobileBgImg: 'LearnMoremobileBg',
    bgImgClass: 'bg-100% bg-no-repeat',
  },
  {
    path: '/subscribe',
    exact: true,
    pageName: 'Subscribe',
    withSidebar: true,
    showBuyButton: true,
    component: Subscribe,
    title: 'Subscribe',
    bgImg: 'commonSectionBg',
    mobileBgImg: 'Mobile404Bg',
    bgImgClass: 'bg-100% bg-no-repeat bg-bottom',
  },
  {
    path: '/partners',
    exact: true,
    pageName: 'Partners',
    withSidebar: true,
    showBuyButton: true,
    component: Partners,
    title: 'Partners',
    bgImg: 'partnersBg',
    mobileBgImg: 'LearnMoremobileBg',
    bgImgClass: 'bg-100% bg-no-repeat bg-center',
  },
  {
    path: '/about-token',
    exact: true,
    pageName: 'About Token',
    withSidebar: true,
    showBuyButton: true,
    component: AboutToken,
    title: 'About the Polkacover Token',
    bgImg: 'aboutTokenBg',
    mobileBgImg: 'AboutTokenMobileBg',
    bgImgClass: 'bg-100% bg-no-repeat',
  },
  {
    path: '/contact-us',
    exact: true,
    pageName: 'Contact Us',
    withSidebar: true,
    showBuyButton: true,
    component: ContactUs,
    title: 'Contact Us',
    bgImg: 'commonSectionBg',
    mobileBgImg: 'ContactUsmobileBg',
    bgImgClass: 'bg-100% bg-no-repeat bg-bottom',
  },
  {
    path: '/cart',
    exact: true,
    pageName: 'Cart',
    withSidebar: false,
    showBuyButton: false,
    component: Cart,
    title: '',
    bgImg: 'cartPageBg',
    mobileBgImg: 'Mobile404Bg',
    bgImgClass: 'bg-fixed bg-right bg-100% bg-no-repeat',
  },
  {
    path: '/product/:type',
    exact: true,
    pageName: 'Product',
    withSidebar: false,
    showBuyButton: false,
    component: Product,
    title: '',
    bgImg: 'productBg',
    mobileBgImg: 'productPageBg',
    bgImgClass: 'bg-100% bg-no-repeat',
  },
  {
    path: '/search/:card',
    exact: true,
    pageName: 'Product details Search',
    withSidebar: false,
    showBuyButton: false,
    component: DetailSearch,
    title: '',
    bgImg: 'packagePageBg',
    mobileBgImg: 'Mobile404Bg',
    bgImgClass: 'bg-fixed bg-center bg-100% bg-no-repeat',
  },
  {
    path: '/about-us',
    exact: true,
    pageName: 'AboutUs',
    withSidebar: true,
    showBuyButton: true,
    component: AboutUs,
    title: 'About Us',
    bgImg: 'aboutUsBg',
    mobileBgImg: 'Mobile404Bg',
    bgImgClass: 'bg-center bg-100% bg-no-repeat',
  },
  {
    path: '/my-insurance',
    exact: true,
    pageName: 'MyInsurance',
    withSidebar: true,
    showBuyButton: false,
    component: MyInsurance,
    title: 'My Insurance',
    bgImg: 'commonSectionBg',
    mobileBgImg: 'Mobile404Bg',
    bgImgClass: 'bg-100% bg-no-repeat bg-bottom',
  },
  {
    path: '/submit-review',
    exact: true,
    pageName: 'Submit Review',
    withSidebar: true,
    showBuyButton: true,
    component: SubmitReview,
    title: 'Submit Review',
    bgImg: 'commonSectionBg',
    mobileBgImg: 'submitReviewBg',
    bgImgClass: 'bg-fixed bg-100% bg-no-repeat bg-bottom',
  },
  {
    path: '/mso-packages',
    pageName: 'MSOProduct',
    withSidebar: false,
    showBuyButton: false,
    component: MsoPackages,
    title: '',
    bgImg: 'packagePageBg',
    bgImgClass: 'bg-100% bg-no-repeat bg-bottom',
  },
  {
    path: '/mso-product',
    exact: true,
    pageName: 'MSO Product',
    withSidebar: false,
    showBuyButton: false,
    component: MsoProducts,
    title: '',
    bgImg: 'productBg',
    bgImgClass: 'bg-100% bg-no-repeat',
  },
  {
    path: '',
    pageName: 'Error',
    withSidebar: true,
    showBuyButton: true,
    component: ErrorPage,
    title: '404',
    bgImg: 'commonSectionBg',
    mobileBgImg: 'Mobile404Bg',
    bgImgClass: 'bg-100% bg-no-repeat bg-bottom',
  },
];

export default routes;
