export const ACTION_METHOD_FAILED = 'ACTION_METHOD_FAILED';

export const LOGIN_MODAL_VISIBLE = 'LOGIN_MODAL_VISIBLE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const REMOVE_ITEM_TO_CART = 'REMOVE_ITEM_TO_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_USER_LOADER = 'SET_USER_LOADER';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const LIST_USER = 'LIST_USER';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';
export const SET_LIST_USER_LOADER = 'SET_LIST_USER_LOADER';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';

export const SEARCH_COVER_LIST = 'SEARCH_COVER_LIST';
export const SEARCH_COVER_LIST_SUCCESS = 'SEARCH_COVER_LIST_SUCCESS';
export const SET_SEARCH_COVER_LIST_LOADER = 'SET_SEARCH_COVER_LIST_LOADER';

export const SEARCH_MSO_LIST = 'SEARCH_MSO_LIST';
export const SEARCH_MSO_LIST_SUCCESS = 'SEARCH_MSO_LIST_SUCCESS';
export const SET_SEARCH_MSO_LIST_LOADER = 'SET_SEARCH_MSO_LIST_LOADER';

export const GET_LOGIN_DETAILS = 'GET_LOGIN_DETAILS';
export const GET_LOGIN_DETAILS_SUCCESS = 'GET_LOGIN_DETAILS_SUCCESS';
export const SET_GET_LOGIN_DETAILS_LOADER = 'SET_GET_LOGIN_DETAILS_LOADER';

export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS';
export const SET_PROFILE_DETAILS_SUCCESS = 'SET_PROFILE_DETAILS_SUCCESS';
export const SET_PROFILE_DETAILS_LOADER = 'SET_PROFILE_DETAILS_LOADER';

export const FETCH_MORE_COVERS = 'FETCH_MORE_COVERS';
export const FETCH_MORE_COVERS_SUCCESS = 'FETCH_MORE_COVERS_SUCCESS';
export const SET_FETCH_MORE_COVERS_LOADER = 'SET_FETCH_MORE_COVERS_LOADER';

export const FETCH_COVERS_WITH_AMOUNT_SUCCESS = 'FETCH_COVERS_WITH_AMOUNT_SUCCESS';

export const GET_QUOTE = 'GET_QUOTE';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const SET_GET_QUOTE_LOADER = 'SET_GET_QUOTE_LOADER';

export const GET_DEVICE_DETAILS = 'GET_DEVICE_DETAILS';
export const GET_DEVICE_DETAILS_SUCCESS = 'GET_DEVICE_DETAILS_SUCCESS';
export const SET_GET_DEVICE_DETAILS_LOADER = 'SET_GET_DEVICE_DETAILS_LOADER';

export const GET_DEVICE_PLAN_DETAILS = 'GET_DEVICE_PLAN_DETAILS';
export const GET_DEVICE_PLAN_DETAILS_SUCCESS = 'GET_DEVICE_PLAN_DETAILS_SUCCESS';
export const SET_GET_DEVICE_PLAN_DETAILS_LOADER = 'SET_GET_DEVICE_PLAN_DETAILS_LOADER';
