export const ACTION_METHOD_FAILED = 'ACTION_METHOD_FAILED';

export const LOGIN_MODAL_VISIBLE = 'LOGIN_MODAL_VISIBLE';
export const REGISTER_MODAL_VISIBLE = 'REGISTER_MODAL_VISIBLE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';

export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';

export const GET_LOGIN_DETAILS = 'GET_LOGIN_DETAILS';
export const GET_LOGIN_DETAILS_SUCCESS = 'GET_LOGIN_DETAILS_SUCCESS';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS';
export const SET_PROFILE_DETAILS_SUCCESS = 'SET_PROFILE_DETAILS_SUCCESS';

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';

export const RESEND_VERIFICATION_EMAIL = 'RESEND_VERIFICATION_EMAIL';
export const RESEND_VERIFICATION_EMAIL_SUCCESS = 'RESEND_VERIFICATION_EMAIL_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_USER_LOADER = 'SET_USER_LOADER';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const LIST_USER = 'LIST_USER';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';
export const SET_LIST_USER_LOADER = 'SET_LIST_USER_LOADER';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';

export const SEARCH_COVER_LIST = 'SEARCH_COVER_LIST';
export const SEARCH_COVER_LIST_SUCCESS = 'SEARCH_COVER_LIST_SUCCESS';
export const SET_SEARCH_COVER_LIST_LOADER = 'SET_SEARCH_COVER_LIST_LOADER';

export const SEARCH_MSO_LIST = 'SEARCH_MSO_LIST';
export const SEARCH_MSO_LIST_SUCCESS = 'SEARCH_MSO_LIST_SUCCESS';
export const SET_SEARCH_MSO_LIST_LOADER = 'SET_SEARCH_MSO_LIST_LOADER';

export const FETCH_MORE_COVERS = 'FETCH_MORE_COVERS';
export const FETCH_MORE_COVERS_SUCCESS = 'FETCH_MORE_COVERS_SUCCESS';
export const SET_FETCH_MORE_COVERS_LOADER = 'SET_FETCH_MORE_COVERS_LOADER';

export const FETCH_COVERS_WITH_AMOUNT_SUCCESS = 'FETCH_COVERS_WITH_AMOUNT_SUCCESS';

export const GET_QUOTE = 'GET_QUOTE';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const SET_GET_QUOTE_LOADER = 'SET_GET_QUOTE_LOADER';

export const GET_DEVICE_DETAILS = 'GET_DEVICE_DETAILS';
export const GET_DEVICE_DETAILS_SUCCESS = 'GET_DEVICE_DETAILS_SUCCESS';
export const SET_GET_DEVICE_DETAILS_LOADER = 'SET_GET_DEVICE_DETAILS_LOADER';

export const GET_DEVICE_PLAN_DETAILS = 'GET_DEVICE_PLAN_DETAILS';
export const GET_DEVICE_PLAN_DETAILS_SUCCESS = 'GET_DEVICE_PLAN_DETAILS_SUCCESS';
export const SET_GET_DEVICE_PLAN_DETAILS_LOADER = 'SET_GET_DEVICE_PLAN_DETAILS_LOADER';

export const GET_DEVICE_MODEL_DETAILS = 'GET_DEVICE_MODEL_DETAILS';
export const GET_DEVICE_MODEL_DETAILS_SUCCESS = 'GET_DEVICE_MODEL_DETAILS_SUCCESS';
export const SET_GET_DEVICE_MODEL_DETAILS_LOADER = 'SET_GET_DEVICE_MODEL_DETAILS_LOADER';

export const SEARCH_BLOG_LIST = 'SEARCH_BLOG_LIST';
export const SEARCH_BLOG_LIST_SUCCESS = 'SEARCH_BLOG_LIST_SUCCESS';
export const SET_SEARCH_BLOG_LIST_LOADER = 'SET_SEARCH_BLOG_LIST_LOADER';

export const SEARCH_BLOG = 'SEARCH_BLOG';
export const SEARCH_BLOG_SUCCESS = 'SEARCH_BLOG_SUCCESS';
export const SET_SEARCH_BLOG_LOADER = 'SET_SEARCH_BLOG_LOADER';

export const FETCH_MORE_BLOGS = 'FETCH_MORE_BLOGS';
export const FETCH_MORE_BLOGS_SUCCESS = 'FETCH_MORE_BLOGS_SUCCESS';
export const SET_FETCH_MORE_BLOGS_LOADER = 'SET_FETCH_MORE_BLOGS_LOADER';
